name = "agents-dot-md"
main = "src/index.js"
compatibility_date = "2025-12-01"

[assets]
directory = "./frontend"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[vars]
GITHUB_CLIENT_ID = ""
PROMPT_REPO_OWNER = "GarrettPeake"
PROMPT_REPO_NAME = "AgentsDotMD"
